version: '3.4'

services:
  privatbank:
    image: ${DOCKER_REGISTRY-}privatbank
    build:
      context: .
      dockerfile: PrivatBank/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}

    env_file:
      - .env 
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672"   # RabbitMQ Default Port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB: PrivatBankDB
    ports:
      - "5432:5432"
    volumes:
    - ./postgres-init-scripts:/docker-entrypoint-initdb.d

  mssql:
  
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    user: root
    volumes:
      - ./mssql-init-scripts:/scripts
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
    entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]

  RequestProcessor:
    image: ${DOCKER_REGISTRY-}requestprocessor
    build:
      context: .
      dockerfile: RequestProcessor/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    env_file:
      - .env 
    depends_on:
      - privatbank
      - rabbitmq
      - postgres
      - mssql